### ISSUE TITLE
Prevent quickfix window from opening

### ISSUE THREAD

**Issue by joalof** [ten3roberts/recipe.nvim#2]
Hi, thanks for the very nice plugin! 

When I execute a simple run recipe for a script, e.g.,  `require('recipe').execute({cmd = 'python %'}):focus({kind = 'float'})`, the quickfix window will always open, even if there are no entries. Is it possible to configure the plugin/recipe such that quickfix will only open if there are errors?

Is it also be possible to have more control over stdout, for instance, I would like to be able to send stdout to a new buffer (opened as a split)?

**Comment by ten3roberts** [comment]
Oh absolutely. The quickfix window opens due to the `qf` component which is attached to the script.

You can disable the `qf` component by feeding `components = { qf = false } ` in the same table as `cmd`.

As for more control over the stdout, there is a component api that is not as documented, but is used by both `qf` and `dap` and any other thing you would want to inspect and hook into a running task.

In your plugin directory you can place a file `recipe/components/myplugin.lua` inside any rtp path such as your config or another plugin `lua/` dir. (you can test by doing `require("recipe.components.myplugin` manually to check that it will be found) to create a custom one, which can then be attached to a recipe with `components { myplugin = {opts}}`.

**Comment by joalof** [comment]
Cheers! I tried with `components = { qf = false } ` and it stops the quickfix windows from appearing altogether, I would still like to parse stderr and have to quickfix open with the locations if there are any errors. What I want is to disable the quickfix window from automatically opening if there are no errors, if possible?

**Comment by ten3roberts** [comment]
Agreed, that is likely a good idea to have.

I'll add an `open = boolean|fun()` and most likely use it myself.

You can at any time override the component configuration for all recipes in the `default_components` in the setup table.

There Are a few areas that have been left after quite a large refactor, so I'll clean those up as well 😊

**Comment by joalof** [comment]
Awesome, thank you! :)

**Comment by ten3roberts** [comment]
Should be done now.

If there is anything more you'd like added feel free to open an issue.

I am using this plugin daily for all my build and debugging tasks, so I currently just implement things as I need them unless there are other requests
